version: "3.8"
services:
  web:
    image: "ghcr.io/jesusdalvarado/jesus-image:latest"
    ports:
      - "5000:5000"
    # volumes:
    #   - ./:/app # This can cause problems when deploying to EB, it would override the files only copying the docker-compose.yml file which is the only file in the S3 bucket
