name: CI/CD
on: # This workflow is triggered on pushes to the repository.
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build: # This workflow contains a single job called "build"
    name: Greetings # This is the name of the job
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Run a one-line script # Runs a single command using the runners shell
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
