name: CI/CD
on: # This workflow is triggered on pushes to the repository.
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build: # This workflow contains a single job called "build"
    name: Greetings # This is the name of the job
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Run a one-line script # Runs a single command using the runners shell
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  push_images:
    name: Publish docker images
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          echo "Running script to publish images"
          sh publish_images.sh ${{ secrets.GH_PAT }}

  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: push_images

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create Terraform resources
        run: |
          terraform init -reconfigure && terraform destroy
        env:
          TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}



  # deploy:
  #   name: Deploy to Elastic Beanstalk
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

      # - run: |
      #   docker build ./modules/webserver/ -t jesusdalvarado-example-image:latest
      #   echo "{{ secrets.GH_PAT }}" | docker login ghcr.io -u jesusdalvarado --password-stdin
      #   docker tag jesusdalvarado-example-image:latest ghcr.io/jesusdalvarado/jesus-image:latest
      #   docker push ghcr.io/jesusdalvarado/jesus-image:latest

      # - name: Build the stack
      #   run: docker-compose -f docker-compose.yml up -d
      # - run: |
      #   echo "{{ secrets.DOCKERHUB_PASSWORD }}" | docker login https://docker.pkg.github.com -u "${{ secrets.DOCKERHUB_USENAME }}" --password-stdin
      #   echo "hello"